# Generated by Django 3.2.7 on 2022-05-12 11:46

from django.db import migrations, models
import django.db.models.deletion
import graphcreate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=40)),
                ('filedescription', models.CharField(max_length=150)),
                ('fileraw', models.FileField(upload_to=graphcreate.models.generate_path_process)),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnname', models.CharField(max_length=150)),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphcreate.uploadedfiles')),
            ],
        ),
    ]
