# Generated by Django 3.2.7 on 2022-05-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphcreate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('equalto', 'equalto'), ('contains', 'contains'), ('contained', 'contained')], default='equalto', max_length=10)),
                ('joincolumnname1', models.CharField(max_length=150)),
                ('joincolumnname2', models.CharField(max_length=150)),
                ('filename1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file1', to='graphcreate.uploadedfiles')),
                ('filename2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file2', to='graphcreate.uploadedfiles')),
            ],
        ),
    ]
