# Generated by Django 3.2.7 on 2022-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcreate', '0002_createrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='entityname',
            field=models.CharField(default='entity', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createrule',
            name='relationship',
            field=models.CharField(choices=[('equalto', 'equalto'), ('contains', 'contains'), ('contained', 'contained'), ('ISA', 'ISA'), ('HAS', 'HAS')], default='equalto', max_length=10),
        ),
    ]
